// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table SampleBicycles (BikepointID:string, Street:string, Neighbourhood:string, Latitude:real, Longitude:real, No_Bikes:long, No_Empty_Docks:long, No_Bikes_1:int, No_Empty_Docks_1:int) 
.create-or-alter table SampleBicycles ingestion json mapping 'SampleBicycles_mapping'
```
[{"Properties":{"Path":"$['BikepointID']"},"column":"BikepointID","datatype":""},{"Properties":{"Path":"$['Street']"},"column":"Street","datatype":""},{"Properties":{"Path":"$['Neighbourhood']"},"column":"Neighbourhood","datatype":""},{"Properties":{"Path":"$['Latitude']"},"column":"Latitude","datatype":""},{"Properties":{"Path":"$['Longitude']"},"column":"Longitude","datatype":""},{"Properties":{"Path":"$['No_Bikes']"},"column":"No_Bikes_1","datatype":""},{"Properties":{"Path":"$['No_Empty_Docks']"},"column":"No_Empty_Docks_1","datatype":""}]
```
